# Generated by Django 3.1 on 2020-08-27 07:11

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_change', models.BooleanField(default=True)),
                ('time_delta', models.DurationField()),
                ('building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timers', to='buildings.building')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timers', to='devices.device')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True)),
                ('state_change', models.BooleanField(default=True)),
                ('time', models.TimeField()),
                ('days_of_week', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=7)),
                ('building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='buildings.building')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='devices.device')),
            ],
        ),
    ]
