# Generated by Django 3.1 on 2020-09-03 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timer',
            name='time_delta',
        ),
        migrations.AddField(
            model_name='timer',
            name='trigger_time',
            field=models.DateTimeField(null=True),
        ),
    ]
