# Generated by Django 3.1 on 2020-08-20 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0004_auto_20200819_1307'),
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timers', to='buildings.building'),
        ),
    ]
