# Generated by Django 3.1 on 2020-08-20 09:10

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_device_created_ts'),
        ('rules', '0002_timer_building'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True)),
                ('state_change', models.BooleanField(default=True)),
                ('time', models.TimeField()),
                ('days_of_week', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=7)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='devices.device')),
            ],
        ),
    ]
