# Generated by Django 3.1 on 2020-08-27 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.SlugField(max_length=8, null=True, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('power', models.SmallIntegerField(null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_ts', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=False)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='devices.device')),
            ],
        ),
    ]
