# Generated by Django 3.1 on 2020-08-15 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='unique_device_id',
            new_name='unique_id',
        ),
    ]
