# Generated by Django 3.1 on 2020-08-15 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
        ('devices', '0002_auto_20200815_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.building'),
        ),
    ]
