# Generated by Django 3.1 on 2020-08-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='power',
            field=models.SmallIntegerField(null=True),
        ),
    ]
