# Generated by Django 3.1 on 2020-08-16 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
        ('devices', '0005_auto_20200816_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='buildings.building'),
        ),
    ]
