# Generated by Django 3.1 on 2020-08-19 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_auto_20200818_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='owner',
        ),
    ]
