# Generated by Django 3.1 on 2020-08-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_remove_device_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
