# Generated by Django 3.1 on 2020-08-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_device_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='created_ts',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
