# Generated by Django 3.1 on 2020-08-21 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0004_auto_20200819_1307'),
        ('devices', '0011_device_created_ts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='buildings.building'),
        ),
    ]
