# Generated by Django 3.1 on 2020-08-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0012_auto_20200821_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='unique_id',
            field=models.SlugField(max_length=8, null=True, unique=True),
        ),
    ]
