# Generated by Django 3.1 on 2020-08-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200819_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='object_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
