# Generated by Django 3.1 on 2020-08-19 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='object_type',
            field=models.CharField(blank=True, choices=[('Device', 'Device'), ('Room', 'Room'), ('Building', 'Building'), ('Scene', 'Scene'), ('Group', 'Group')], max_length=15, null=True),
        ),
    ]
