# Generated by Django 3.1 on 2020-08-19 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0004_auto_20200819_1307'),
        ('events', '0004_event_object_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='buildings.building'),
        ),
    ]
