# Generated by Django 3.1 on 2020-08-20 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_device_created_ts'),
        ('events', '0005_event_building'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='object_type',
        ),
        migrations.AddField(
            model_name='event',
            name='device_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='devices.device'),
        ),
    ]
