# Generated by Django 3.1 on 2020-08-20 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20200820_0837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='device_id',
            new_name='device',
        ),
    ]
