# Generated by Django 3.1 on 2020-08-16 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
        ('rooms', '0002_auto_20200816_0630'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_group', to='buildings.building')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='room_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='rooms.roomgroup'),
        ),
    ]
