# Generated by Django 3.1 on 2020-08-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceHourlyUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('device', models.IntegerField()),
                ('usage', models.DecimalField(decimal_places=2, max_digits=8)),
                ('runtime', models.IntegerField()),
            ],
        ),
    ]
