# Generated by Django 3.1 on 2020-09-03 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviceHourlyUsage',
        ),
    ]
