# Generated by Django 3.1 on 2020-08-18 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='buildings.building'),
        ),
    ]
