# Generated by Django 3.1 on 2020-08-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_remove_device_owner'),
        ('buildings', '0003_group_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='devices',
            field=models.ManyToManyField(related_name='groups', to='devices.Device'),
        ),
    ]
